### ISSUE TITLE
About page size

### ISSUE THREAD

**Issue by lambogini1992** [viktorvano/STM32F3Discovery_internal_FLASH#1]
Hi Viktor!
Please help me know about page_size!
Why are you evaluate 0x800 for the define?
I was check in datasheet they talk that the size of page is 1 or 2 Kb

Thanks

**Comment by viktorvano** [comment]
Yes, page size is 2kB. A number 0x800 is in decimal 2048 and it is 2kB.
Datasheet says that at page 82 ("Page (2 KB) erase time"): https://www.st.com/resource/en/datasheet/stm32f303cb.pdf

And also a generated code (file: "stm32f3xx_hal_flash_ex.h"): 
/** @defgroup FLASHEx_Page_Size FLASHEx Page Size
  * @{
  */
#define FLASH_PAGE_SIZE          0x800
